### ISSUE TITLE
Can't see docs for "Deno.connect"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/docland#1]
https://doc-land.deno.dev/deno/stable ->
https://doc-land.deno.dev/deno/stable/~/Deno ->
https://doc-land.deno.dev/deno/stable/~/Deno.connect 

![Screenshot 2021-12-03 at 14 08 19](https://user-images.githubusercontent.com/13602871/144607661-5b05a037-af99-4f78-85e8-3e6d49a00ec2.png)

**Comment by kitsonk** [comment]
Hmmmm... that is strange... That shouldn't happen.

**Comment by kitsonk** [comment]
Ok, something is wrong, as there is a duplication of some of the sections in the namespace and the table of contents is missing.  I think something is wrong with the namespace merging.

**Comment by bartlomieju** [comment]
As another data point: `Deno.connect` is available in both stable and unstable namespace. Can this interfere somehow?

**Comment by kitsonk** [comment]
It shouldn't... `connectTls` is broken too...
