### ISSUE TITLE
no copyable import 

### ISSUE THREAD

**Issue by ry** [denoland/docland#103]
https://doc.deno.land/https://deno.land/std@0.125.0/http/file_server.ts/~/serveFile
<img width="1440" alt="Screen Shot 2022-02-11 at 10 10 13 PM" src="https://user-images.githubusercontent.com/80/153694470-60b3dfe5-378b-4ea1-811c-eca3f880a515.png">

**Comment by kitsonk** [comment]
We only added the import for the root module: https://doc.deno.land/https://deno.land/std@0.125.0/http/file_server.ts

Adding it for individual symbol imports though makes sense.
