### ISSUE TITLE
 Issues with nano_jsx > 0.0.21?

### ISSUE THREAD

**Issue by yandeu** [denoland/docland#106]
I just read [this line](https://github.com/denoland/docland/blob/9941a00b6825e01ceab0dc28435ec5101c5c5131/deps.ts#L107) and wanted to offer my help.

**Comment by kitsonk** [comment]
Thanks... I will take a look at it again this week. I think for a while I couldn't do anything on nano_jsx repo because I hadn't contributed before, or something like that, so I didn't open an issue at the time.

**Comment by yandeu** [comment]
Looks like it has been fixed with nano_jsx@30?

https://github.com/denoland/docland/blob/08d6ad20ad3727feafaa0811590927b74ba96651/deps.ts#L109

**Comment by kitsonk** [comment]
Yes, no problems with 0.30. 😄
