### ISSUE TITLE
`export { default as random } from 'https://cdn.skypack.dev/lodash@4.17.21/random?dts'` failed

### ISSUE THREAD

**Issue by masx200** [denoland/docland#194]
`export { default as random } from 'https://cdn.skypack.dev/lodash@4.17.21/random?dts'` failed

https://cdn.jsdelivr.net/gh/masx200/leetcode-test@10.7.2/deps.ts

https://doc.deno.land/https://cdn.jsdelivr.net/gh/masx200/leetcode-test@10.7.2/deps.ts

https://doc.deno.land/https://cdn.skypack.dev/lodash@4.17.21/random?dts

**Comment by masx200** [comment]
```ts
import { random } from "./index.d.ts";
export = random;

```

**Comment by masx200** [comment]
https://cdn.skypack.dev/-/lodash@v4.17.21-K6GEbP02mWFnLA45zAmi/dist=es2019,mode=types/random.d.ts

https://esm.sh/v96/@types/lodash@4.14.186/random~.d.ts

**Comment by kitsonk** [comment]
These type definitions use `export =` which is not "valid" from the perspective of Deno CLI (it is incompatible with ES modules and therefore incompatible with Deno) nor for documentation purposes.

It is currently a design limitation.
