### ISSUE TITLE
Namespaced docs dont find other namespaced symbols for linking

### ISSUE THREAD

**Issue by Sembiance** [denoland/docland#25]
Not sure if this is the write repo to file this issue...

In the new updated docs at: https://doc.deno.land/deno/stable/~/Deno.run
It shows that it returns a `Process<T>` but `Process` is no longer a hyperlink to the docs page for that type, so I have to manually go back and find the `Process` type manually.

In the old stable docs, if you looked at Deno.run, you could click on `Process` to be taken to the docs for that type.

For newbies like myself, being able to click those custom types and see what they are was very useful.

**Comment by kitsonk** [comment]
It does work in some instances, it is just that `Deno.run` is only looking for a top level symbol of `Process` instead of `Deno.Process` first, and then `Process`.
