### ISSUE TITLE
Adjust colors to be more accessible for colorblind users

### ISSUE THREAD

**Issue by bartlomieju** [denoland/docland#4]
It's very hard for me to distinguish colors used in "Namespace" and "Classes" sections due to colorblindness:
https://doc-land.deno.dev/deno/stable/~/Deno

(these are actually the two colors I have troubles with so it's just a bad coincidence, but hopefully we can make them more accessible)

**Comment by kitsonk** [comment]
We have 7 different types of nodes we are display, there isn't 7 distinctly different color.  The contrast is with WCAG AA guidelines on all the colors.  I think the only other option would be to just eliminate them, as the items are broken into clearly defined sections.

**Comment by bartlomieju** [comment]
The font is quite thin at the moment, maybe we could make them bold, it helps a lot:
![Screenshot 2021-12-03 at 14 57 30](https://user-images.githubusercontent.com/13602871/144614414-e390fa55-2f69-45a7-bf64-cc8080e69b87.png)

**Comment by kitsonk** [comment]
that makes sense
