### ISSUE TITLE
support `@link` JSDoc syntax

### ISSUE THREAD

**Issue by asos-craigmorten** [denoland/docland#46]
The old docs website supported the JSDoc `@link` syntax. Reference: https://jsdoc.app/tags-inline-link.html

This is a feature request for equal support of this directive on the new Deno docs website.

References:

- Location of pertinent code on old docs site: https://github.com/denoland/doc_website/blob/41eef09684f7fc33f8930f93ca2caa2881c39036/components/JSDoc.tsx#L15

Loosely related:

- https://github.com/denoland/doc_website/issues/205
- https://github.com/denoland/doc_website/issues/228

**Comment by jaydenseric** [comment]
Also `@linkcode`, which is both JSDoc and TypeScript syntax.
