### ISSUE TITLE
Support JSDoc's `@example`

### ISSUE THREAD

**Issue by Im-Beast** [denoland/docland#53]
I would like to see doc.deno.land supporting `@example` tag – https://jsdoc.app/tags-example.html.

Example of using such tag:
 - https://github.com/Im-Beast/deno_tui/blob/7ab514cb31abb9ac96f509fde2942a0851b161bb/src/event_emitter.ts#L43

**Comment by kitsonk** [comment]
It looks like vscode handles these on hover text. We should as well. Going to need support in `deno_doc` first.
