### ISSUE TITLE
Integrate into Google Analytics

### ISSUE THREAD

**Issue by kitsonk** [denoland/docland#65]
We should integrate it into Google Analytics to provide better insight on what documentation folks are looking at and help identify any rending issues.

Ping @piscisaureus

**Comment by ry** [comment]
Most of the logic can be copied from https://github.com/denoland/dotland/blob/8e71a4432111f7b938f1060b1f276d893b0bb15d/worker/analytics.ts

I wonder if it makes sense to abstract this code out into a deno.land/x/serverside_ga module that could be shared between dotland and docland.

a dotcom blog post / tutorial explaining how to do this would be awesome.

**Comment by kitsonk** [comment]
Yeah, it makes sense to abstract this out a bit better and make it easily re-usable and add it to deno.land/x.  I will look to do that.
