### ISSUE TITLE
dnt documentation doesn't load

### ISSUE THREAD

**Issue by ry** [denoland/docland#76]
https://doc.deno.land/https://deno.land/x/dnt@0.10.0/mod.ts

**Comment by kitsonk** [comment]
The real fix for this is: denoland/deno_graph#95

**Comment by kitsonk** [comment]
I incorporated the PR associated with denoland/deno_graph#95 all the way upstream and made a deployment here that contains the change: https://cold-weasel-28.deno.dev/https://deno.land/x/dnt@0.10.0/mod.ts which now loads for me.

ping @dsherret

**Comment by kitsonk** [comment]
Ack, deno_graph wasn't updated to build type only graphs.  Need to do that before we can close this.
